config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: 'pages#home'
  resources :users, only: [:show]
  resources :spaces do
    collection do
      post 'update_dates'
    end
    resources :reservations, only: [:new, :create, :index]
  end
end

app/models/reservation.rb
class Reservation < ActiveRecord::Base

  belongs_to :space
  belongs_to :user

  validates :start_date, :end_date, presence: true

end

app/models/space.rb
class Space < ActiveRecord::Base

  CATEGORIES_EQUIPMENTS = ["Internet","Kitchen", "Projector", "Board", "Furniture"]
  TYPE_OF_SPACE = ["Standing","Parliament", "Banquet", "U-Shape", "Theatre"]

  belongs_to :user
  has_many :reservations, dependent: :destroy
  accepts_nested_attributes_for :reservations

 validates :title, presence: true, length: { maximum: 20 }
 validates :address, presence: true, uniqueness: true
 validates :availability, inclusion: { in: [true, false]}
 validates :price_per_day, :nb_of_pers, :description, presence: true
 validates :equipements, presence: true
 validates :type_of_space, presence: true, inclusion:{ in: TYPE_OF_SPACE }

  has_attached_file :picture,
    styles: { medium: "300x300>", thumb: "100x100>" }

  validates_attachment_content_type :picture,
    content_type: /\Aimage\/.*\z/

  geocoded_by :address
  after_validation :geocode, if: :address_changed?
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
        :omniauthable, omniauth_providers: [:facebook]
  has_many :spaces
  has_many :reservations

  def self.find_for_facebook_oauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]  # Fake password for validation
      user.first_name = auth.info.first_name
      user.last_name = auth.info.last_name
      user.picture = auth.info.image
      user.token = auth.credentials.token
      user.token_expiry = Time.at(auth.credentials.expires_at)
    end
  end
end

  # validates :first_name, :last_name, :user_name, :password, presence: true
  # validates :username, :email, uniqueness: true
  # validates :email, presence: true, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/, message: "invalid email" }
  # validates :password, length: { minimum: 8}, unless: "password.nil?"
  # validates :password, presence: true, if: "id.nil?"

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :find_space, only: [ :new, :create ]
  def home
    @space = Space.new
    @reservation = @space.reservations.new
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :find_space, only: [ :new, :create ]

  def index
    @reservations = Reservation.where(user_id: current_user.id)
  end

  def new
    @checkin = session["checkin"]
    @checkout = session["checkout"]
    @reservation = Reservation.new
    @total_price = @space.price_per_day*5
  end

  def create

    @reservation = @space.reservations.build(reservation_params)
    if @reservation.save
      redirect_to user_path(current_user)
    else
      render :new
    end
  end

  private

  def reservation_params
    params.require(:reservation).permit(:start_date, :end_date, :user_id  )
  end
  def find_space
    @space = Space.find(params[:space_id])
  end
end

app/controllers/spaces_controller.rb
class SpacesController < ApplicationController

  before_action :set_space, only: [:show, :edit, :update, :destroy ]
#  before_action :set_user, only: [:new, :create, :update]

  def index
    @spaces = Space.all

    @markers = Gmaps4rails.build_markers(@spaces) do |space, marker|
      marker.lat space.latitude
      marker.lng space.longitude
    end

    @start_date = params[:start_date]
    @end_date = params[:end_date]
    session["checkin"] = @start_date
    session["checkout"] = @end_date

  end

  def update_dates
    # params == { name: "checkin", value: "12/04/1224"}
    session[params[:name]] = params[:value]
    head 200
  end

  def show
    @checkin = session["checkin"]
    @checkout = session["checkout"]
    @space = Space.find(params[:id])
    @space_coordinates = { lat: @space.latitude, lng: @space.longitude }
    @alert_message = "You are viewing {@space.name}"
  end

  def new
    if user_signed_in?
      @space = Space.new
    else
      redirect_to root_path
    end
  end

  def create
    @space = Space.new(space_params)
    @space.user = current_user
    equipements = params[:space][:equipements][0, params[:space][:equipements].size - 1]*', '
    @space.equipements = equipements
    range_of_pers = params[:space][:nb_of_pers]
    case range_of_pers
    when "1..10"
      nb_of_pers = 1
    when "10..20"
      nb_of_pers = 10
    when "20..30"
      nb_of_pers = 20
    else
      nb_of_pers = 30
    end
    @space.nb_of_pers = nb_of_pers
    if @space.save
     redirect_to user_path(current_user)
    else
      render :new
    end
  end

  def edit
  end

  def update
  end

  def destroy
    @space = Space.find(params[:id])
    @space.destroy
    redirect_to spaces_path(@space)
  end

  private

  def set_space
    @space = Space.find(params[:id])
  end

  def space_params
    params.require(:space).permit(:title, :address, :price_per_day, :description, :type_of_space, :picture, :availability)
  end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    user = User.find_for_facebook_oauth(request.env['omniauth.auth'])

    if user.persisted?
      sign_in_and_redirect user, event: :authentication
      set_flash_message(:notice, :success, kind: 'Facebook') if is_navigational_format?
    else
      session['devise.facebook_data'] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show

  @user = User.find(params[:id])

  end

end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/spaces_helper.rb
module SpacesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TODO</title>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= render 'shared/footer' %>

    <%= javascript_include_tag "https://maps.google.com/maps/api/js?sensor=false" %>
    <%= javascript_include_tag "https://google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js" %>
    <%= javascript_include_tag 'application' %>

    <%= yield(:after_js) %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner" style="background-image: url('https://images.unsplash.com/uploads/1412739483594d16c8046/a9a53469?ixlib=rb-0.3.5&q=80&fm=jpg&s=cb33c30f6fe3457eb2d511abcc60c839')">
  <div class="container">
    <div class="row">
      <div class="banner-gradient"></div>
      <div class="banner-content text-center">
        <h1>RENT AN AWESOME SPACE</h1>
        <p>Probably one of the best homepage of the day</p>
        <div class="row padded text-center jumbotron">
          <h3>NEED A SPACE ?</h3>
          <p class="Enter a City"></p>
          <%= simple_form_for @space, url: spaces_path, method: :get do |f| %>
            <div class="col-xs-12 col-sm-3">
              <p><%= text_field_tag :start_date, nil, class: "datepicker", placeholder: "Check-in" %></p>
            </div>
            <div class="col-xs-12 col-sm-3">
              <p><%= text_field_tag :end_date, nil, class: "datepicker", placeholder: "Check-out" %></p>
            </div>
            <div class="col-xs-12 col-sm-3">
            <%= f.input :type_of_space, collection: Space::TYPE_OF_SPACE %>
            </div>
            <div class="col-xs-12 col-sm-3">
            <%= f.submit "Search", class: "btn btn-primary btn-lg" %>
            </div>
          <% end %>
          <p class="home-description-text"></p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/reservations/_card.html.erb
<!-- Code à revoir -->
<div class="card">
  <span class="card-bg" style="background-image:url(<%= reservation.space.picture.url %>)"></span>
  <span class="card-shadow"></span>
  <span class="card-text">
    <h2><%= reservation.space.title %></h2>
    <p><%= reservation.space.address %></p>
  </span>
  <%= link_to "",reservation_path(reservation), class: "card-link" %>
</div>

app/views/reservations/index.html.erb
<!-- Code à revoir -->
<div class="container">
  <%if @reservations.length == 0%>
    <h2 class="text-center"><%="You have no resa yet!"%></h2>
  <%else%>
  <h2 class="text-center">Overview of my resa </h2>
  <div class="row">
    <% @reservations.each do |reservation| %>
      <div class="col-xs-12 col-md-6">
        <%= render "card", reservation: reservation %>
      </div>
    <%end%>
  <%end%>
  </div>
</div>

app/views/reservations/new.html.erb
<!-- app/views/reservation/new.html.erb -->
<div class="text-center">
  <div class="container">
    <div class="row">
      <div class="col-sm-6 col-sm-offset-3 ">

        <h2>Confirm Booking Request</h2>
        <br>
        <div class="card" z-default=10 z-hover=30 >
          <h3> Your Arrival : <%= @checkin %></h3>
        </div>

        <div class="card" z-default=30 z-hover=70>
          <h3> Your Departure : <%= @checkout %></h3>
        </div>

        <div class="card" z-default=30 z-hover=70>
          <h3> Price : <%= @total_price %> €</h3>
        </div>
       <%=simple_form_for [@space, @reservation] do |f| %>
         <%= f.input :start_date, :as => :hidden, :input_html => {:value => @checkin} %>
         <%= f.input :end_date, :as => :hidden, :input_html => {:value => @checkout} %>
         <%= f.input :user_id, :as => :hidden, :input_html => {:value => current_user.id} %>
         <%=  f.submit "accept", class: "btn btn-primary  " %>
          <%= link_to 'decline', root_path, class: 'btn btn-danger' %>
         <% end -%>




        </div>
      </div>
    </div>
  </div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer-distributed">

      <div class="footer-left">

        <h3>Share Space</h3>

        <p class="footer-text">
          Réalisé avec <%= image_tag("coeur.png", :alt => "rss feed", :width => 20, :height => 20) %> par la Front-end Team du Wagon. <br><br>Oscar, Ricardo et David.
        </p>
      </div>

      <div class="footer-center">

        <div>
          <i class="fa fa-map-marker"></i>
          <p><span>16 villa Gaudelet</span> Paris, France</p>
        </div>

        <div>
          <i class="fa fa-phone"></i>
          <p>No phone, no problem !</p>
        </div>

        <div>
          <i class="fa fa-envelope"></i>
          <p><a href="mailto:support@company.com">support@sharespace.com</a></p>
        </div>

      </div>

      <div class="footer-right">

        <p class="footer-company-about">
          <span>About Share Space</span>
          Share Space est une compagnie fictive crée par la team front-end du Wagon
        </p>

        <div class="footer-icons">
          <a href="#"><i class="fa fa-facebook"></i></a>
          <a href="#"><i class="fa fa-twitter"></i></a>
          <a href="#"><i class="fa fa-linkedin"></i></a>
          <a href="#"><i class="fa fa-github"></i></a>
        </div>

      </div>

    </footer>

app/views/shared/_navbar.html.erb
<nav class="navbar-wagon">
  <div class="container navbar-wagon-container">

    <a href="">
      <%= link_to (image_tag("logo.png", :alt => "home image", :width => 70, :height => 70)), root_path %>
    </a>

    <div class="navbar-wagon-pusher"></div>
    <hr class="hidden-xs hidden-sm">
    <% if user_signed_in? %>
      <%= link_to "", class: "navbar-wagon-item navbar-wagon-link hidden-xs" do %>
        <div class="icon-badge-container">
          <i class="fa fa-envelope-o"></i>
          <div class="icon-badge icon-badge-blue"></div>
        </div>
      <% end %>
      <hr>
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= image_tag current_user.picture, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>

          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to current_user do %>
                <i class="fa fa-user"></i> <%= t ".profile", default: "Profile" %>
              <% end %>
            </li>
            <li>
              <%= link_to "/" do %>
                <i class="fa fa-home"></i>  <%= t ".profile", default: "Home" %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t ".sign_out", default: "Log out" %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <%= link_to "Sign in with Facebook", omniauth_authorize_path('user', 'facebook'), class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
    <hr>
    <%= link_to "Login", new_user_registration_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <hr>
    <%= link_to  t( ".top_call_to_action", default: "Add a space"), new_space_path, class: "navbar-wagon-item navbar-wagon-button btn" %>
  </div>
</nav>

app/views/spaces/_card.html.erb
<div class="card">
  <span class="card-bg" style="background-image:url('<%= image_url space.picture.url(:medium) %>')"></span>
  <span class="card-text">
    <h2><%=space.title %></h2>
    <p><%=space.price_per_day %></p>
  </span>
  <span class="card-user">
    <img src="<%= space.picture.url(:thumb) %>" class="avatar avatar-bordered"/>
  </span>
  <%= link_to "", space_path(space), class: "card-link updated-link" %>
</div>

app/views/spaces/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-8">
      <div class="searchbar">
        <div class="well">
          Filter by price Pitchoune:
          <b>€ 10</b>
          <div class="slider slider-horizontal" style="width: 414px;">
            <div class="slider-track">
              <div class="slider-selection" style="left: 24.2424%; width: 20.202%;"></div>
              <div class="slider-handle round" style="left: 24.2424%;"></div>
            </div>
            <div class="tooltip top" style="top: -40px; left: 111.182px;">
              <div class="tooltip-arrow"></div>
              <div class="tooltip-inner">250 : 450</div>
            </div><input type="text" class="span2" value="" data-slider-min="10" data-slider-max="1000" data-slider-step="5" data-slider-value="[250,450]" id="sl2"></div>
            <b>€ 1000</b>
        </div>
      </div>
      <div class="jesaispas jumbotron">
        <h5>Change the date Pitchoune</h5>
        <input type="text" class="datepicker update-link" name="checkin" value="<%= @start_date %>" placeholder: "Check-in">
        <input type="text" class="datepicker update-link" name="checkout" value="<%= @end_date %>" placeholder: "Check-out">
        <br>
      </div>
      <div class="search-results">
        <% @spaces.each do |space| %>
          <div class="col-xs-12 col-sm-4">
          <%= render "card", space: space %>
          </div>
        <% end %>
      </div>
    </div>
  <div class="row">
    <hr class="hidden" />
      <div class="col-xs-12 col-sm-4">
        <div id="map" style="width: 500px; height: 600px;"></div>
        <% content_for(:after_js) do %>
          <%= javascript_tag do %>
            $(document).on('ready', function() {
              handler = Gmaps.build('Google');
              handler.buildMap({ internal: { id: 'map' } }, function(){
                markers = handler.addMarkers(<%= raw @markers.to_json %>);
                handler.bounds.extendWith(markers);
                handler.fitMapToBounds();
              });
            })
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/spaces/new.html.erb
<div class="panel panel-default">
  <div class="class panel-heading text-center">
    Create your beautiful space
  </div>
  <div class="class panel-body">
    <div class="class container">
      <%= simple_form_for @space do |f| %>

      <div class="row">
        <div class="class col-md-4 select">
          <div class="form-inputs">
            <%= f.input :title, required: true %>
          </div>
        </div>

        <div class="class col-md-4 select">
          <div class="form-inputs">
            <%= f.input :address, required: true %>
          </div>
        </div>

        <div class="class col-md-4 select">
          <div class="form-inputs">
            <%= f.input :price_per_day, required: true %>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="class col-md-4">
        <%= f.input :equipements, collection: Space::CATEGORIES_EQUIPMENTS, as: :check_boxes  %>
        </div>

        <div class="class col-md-4">
          <%= f.input :type_of_space, required: true, collection: ["Standing","Parliament", "Banquet", "U-Shape", "Theatre"] %>
        </div>

        <div class="class col-md-4">
          <%= f.input :nb_of_pers, required: true, collection: [1..10,10..20, 20..30, "More than 30"] %>
        </div>
      </div>

      <div class="row">
        <div class="class col-md-4">
          <%= f.input :description, required: true %>
        </div>

        <div class="class col-md-4">
          <%= f.input :availability, required: true %>
        </div>

        <div class="class col-md-4">
          <%= f.input :picture %>
        </div>
      </div>

      <div class="row text-center">
        <div class="col-sm-12">
          <div class="actions ">
            <%= f.submit "Create the Space", class: "btn btn-danger" %>
          </div>
        </div>
      </div>


    </div>
  </div>
</div>
<%end%>

app/views/spaces/show.html.erb
<ul class="bxslider">
  <li class="card-bg"><%= image_tag "slider1.jpg" %></li>
  <li class="card-bg slide"><%= image_tag "slider2.jpg" %></li>
  <li class="card-bg slide"><%= image_tag "slider3.jpg" %></li>
</ul>

<div class="container">
  <div class="col-xs-12 col-md-8 ">
    <div class="row page-header">
      <h3><%= @space.title %></h3>
    </div>
    <div class="row jumbotron">
      <div class="col-xs-12 col-md-3 ">
        <h4>Global info</h4>
        <h5>Type of space: <%= @space.type_of_space %></h5>
        <h5>Price: <%= @space.price_per_day %> €</h5>
        <h5>Address: <%= @space.address %></h5>
        <h5>Equipments: <%= @space.equipements %></h5>
        <h5><%= @space.nb_of_pers %> pers</h5>
      </div>
      <div class="col-xs-12 col-md-6 ">
        <h4>Description</h4>
        <h5><%= @space.description %></h5>
      </div>
      <div class="col-xs-12 col-md-3 ">
        <span class="card-bg"><%= image_tag @space.picture.url(:thumb) %></span>
      </div>
    </div>
  </div>
  <div class="col-xs-12 col-md-4">
    <div class="informations margin jumbotron">
      <div class="title page-header">
        <h3>Your booking information</h3>
      </div>
      <%= simple_form_for [@space, @space.reservations.new], url: new_space_reservation_path(@space), method: :get do |f| %>
      <div class="row text-center">
        <p><%= f.input :start_date, as: :string, input_html: { class: "datepicker", placeholder: "Check-in", value: @checkin } %></p>
      </div>
      <div class="row text-center">
        <p><%= f.input :end_date, as: :string, input_html: {  class: "datepicker", placeholder: "Check-out", value: @checkout } %></p>
      </div>
      <div class="row text-center">
      <%= f.submit "Request to Book Bro", class: "btn btn-primary btn-lg" %>
      </div>
      <% end %>
    </div>
  </div>
</div>

<div>

<% content_for(:after_js) do %>
  <%= javascript_tag do %>
    $(document).ready(function() {
      var coord = <%= raw @space_coordinates %>;
      alert('Flat coordinates are ' + coord.lat + ', ' + coord.lng);
    });
  <% end %>
<% end %>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-4">
      <div class="panel panel-success">
        <div class="panel-heading">Hello <%=@user.first_name %> |  <%= link_to "Edit my profil", edit_user_registration_path %></div>
        <div class="panel-body">
          <ul>
          <li><p><span></span> <%= @user.email %></p></li><br>
          <div class="profil_picture "><%= image_tag @user.picture %></div>
          </ul>
        </div>
      </div>
    </div>




  <div class="row">
    <div class="col-md-7">
        <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
          <div class="panel panel-success">
            <div class="panel-heading" role="tab" id="headingOne">
              <h4 class="panel-title">
                <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                  Your Reservations
                </a>
              </h4>
            </div>
              <div id="collapseOne" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="headingOne">
                <div class="panel-body">

                   <% @user.reservations.each do |resa|%><br>

                     <li><p><span>Type of space : </span><%= resa.space.type_of_space %></p></li>
                     <li><p><span>Début de la réservation</span> :<%= resa.start_date %></p></li>
                     <li><p><span>Fin de votre réservation</span> :<%= resa.end_date %></p></li>
                    <li><p><span>Adresse de votre réservation</span> :<%= resa.space.address %></p></li>
                    <li><p><span class="label label-success">Price</span> <%= resa.total_price %>€</p></li>
                  <%end%>
                </div>
              </div>
            </div>
          </div>
          <div class="panel panel-success">
            <div class="panel-heading" role="tab" id="headingTwo">
              <h4 class="panel-title">
                <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                  Your Spaces
                </a>
              </h4>
            </div>
            <div id="collapseTwo" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingTwo">
              <div class="panel-body">
                  <% @user.spaces.each do |space|%><br>
                 <li><p>
                  <% if @user.spaces.empty? %>
                    "You have no reservation"
                  <% else %>
                  <%= space.title %></p>
                </p></li>
                 <li><p>Address <%= space.address %>
                </p></li>
                </li>
                 <li><p>Capacity <%= space.nb_of_pers %>
                </p></li>
                <p><%= image_tag space.picture.url(:thumb) %>
                </p>
                 <%end%>
                <%end%>
            </div>
          </div>
        </div>
      </div>
      </div>
     </div>
    </div>
  </div>
</div>